SWEP.UsesEmptyAnims = true

SWEP.Sequences = {
	base_crawl	=	"base_crawl",
	base_down	=	"base_down",
	base_draw	=	"base_draw",
	base_dryfire	=	"base_dryfire",
	base_fire	=	"base_fire",
	base_firelast	=	"base_firelast",
	base_holster	=	"base_holster",
	base_idle	=	"base_idle",
	base_ready	=	"base_ready",
	base_reload	=	"base_reload",
	base_reloadempty	=	"base_reloadempty",
	base_sprint	=	"base_sprint",
	
	deployed_dryfire	=	"deployed_dryfire",
	deployed_empty	=	"deployed_empty",
	deployed_empty_dryfire	=	"deployed_empty_dryfire",
	deployed_empty_in	=	"deployed_empty_in",
	deployed_empty_out	=	"deployed_empty_out",
	deployed_fire	=	"deployed_fire",
	deployed_firelast	=	"deployed_firelast",
	deployed_idle	=	"deployed_idle",
	deployed_in	=	"deployed_in",
	deployed_iron_dryfire	=	"deployed_iron_dryfire",
	deployed_iron_fire	=	"deployed_iron_fire",
	deployed_iron_fire_last	=	"deployed_iron_fire_last",
	deployed_out	=	"deployed_out",
	deployed_reload	=	"deployed_reload",
	deployed_reloadempty	=	"deployed_reloadempty",
	
	empty_crawl	=	"empty_crawl",
	empty_down	=	"empty_down",
	empty_draw	=	"empty_draw",
	empty_holster	=	"empty_holster",
	empty_idle	=	"empty_idle",
	empty_iron_down	=	"iron_empty_down",
	empty_iron_idle	=	"iron_empty_idle",
	empty_layer	=	"empty_layer",
	empty_sprint	=	"empty_sprint",
	
	foregrip_crawl	=	"foregrip_crawl",
	foregrip_down	=	"foregrip_down",
	foregrip_draw	=	"foregrip_draw",
	foregrip_dryfire	=	"foregrip_dryfire",
	foregrip_fire	=	"foregrip_fire",
	foregrip_firelast	=	"foregrip_firelast",
	foregrip_holster	=	"foregrip_holster",
	foregrip_iron_down	=	"foregrip_iron_down",
	foregrip_iron_dryfire	=	"foregrip_iron_dryfire",
	foregrip_iron_fire	=	"foregrip_iron_fire",
	foregrip_iron_firelast	=	"foregrip_iron_firelast",
	foregrip_ready	=	"foregrip_ready",
	foregrip_reload	=	"foregrip_reload",
	foregrip_reloadempty	=	"foregrip_reloadempty",
	foregrip_sprint	=	"foregrip_sprint",
	
	foregrip_empty_crawl	=	"foregrip_empty_crawl",
	foregrip_empty_down	=	"foregrip_empty_down",
	foregrip_empty_draw	=	"foregrip_empty_draw",
	foregrip_empty_holster	=	"foregrip_empty_holster",
	foregrip_empty_idle	=	"foregrip_empty_idle",
	foregrip_empty_iron	=	"foregrip_empty_iron",
	foregrip_empty_iron_down	=	"foregrip_empty_iron_down",
	foregrip_empty_sprint	=	"foregrip_empty_sprint",
	
	idle	=	"idle",
	iron_down	=	"iron_down",
	iron_dryfire	=	"iron_dryfire",
	iron_fire	=	"iron_fire",
	iron_firelast	=	"iron_firelast",
}
