SWEP.Sequences = {
	base_crawl	=	"base_crawl",
	base_down	=	"base_down",
	base_draw	=	"base_draw",
	base_dryfire	=	"base_dryfire",
	base_fire	=	"base_fire",
	base_fireselect	=	"base_fireselect",
	base_holster	=	"base_holster",
	base_idle	=	"base_idle",
	base_ready	=	"base_ready",
	base_reload	=	"base_reload",
	base_reloadempty	=	"base_reloadempty",
	base_sprint	=	"base_sprint",
	
	deployed_dryfire	=	"deployed_dryfire",
	deployed_fire	=	"deployed_fire",
	deployed_fireselect	=	"deployed_fireselect",
	deployed_idle	=	"deployed_idle",
	deployed_in	=	"deployed_in",
	deployed_out	=	"deployed_out",
	deployed_reloadempty	=	"deployed_reload_empty",
	deployed_reload	=	"deployed_reload_half",
	
	deployed_iron	=	"deployed_iron",
	deployed_iron_dryfire	=	"deployed_iron_dryfire",
	deployed_iron_fire	=	{"deployed_iron_fire_1", "deployed_iron_fire_2"},
	deployed_iron_fire_1	=	"deployed_iron_fire_1",
	deployed_iron_fire_2	=	"deployed_iron_fire_2",
	deployed_iron_fireselect	=	"deployed_iron_fireselect",
	
	foregrip_crawl	=	"foregrip_crawl",
	foregrip_down	=	"foregrip_down",
	foregrip_draw	=	"foregrip_draw",
	foregrip_dryfire	=	"foregrip_dryfire",
	foregrip_fire	=	"foregrip_fire",
	foregrip_fireselect	=	"foregrip_fireselect",
	foregrip_holster	=	"foregrip_holster",
	foregrip_ready	=	"foregrip_ready",
	foregrip_reload	=	"foregrip_reload",
	foregrip_reloadempty	=	"foregrip_reloadempty",
	foregrip_sprint	=	"foregrip_sprint",
	
	foregrip_iron_down	=	"foregrip_iron_down",
	foregrip_iron_dryfire	=	"foregrip_iron_dryfire",
	foregrip_iron_fire	=	"foregrip_iron_fire",
	foregrip_iron_fireselect	=	"foregrip_iron_fireselect",
	
	gl_crawl	=	"gl_crawl",
	gl_down	=	"gl_down",
	gl_draw	=	"gl_draw",
	gl_dryfire	=	"gl_dryfire",
	gl_fire	=	"gl_fire",
	gl_fireselect	=	"gl_fireselect",
	gl_holster	=	"gl_holster",
	gl_ready	=	"gl_ready",
	gl_reload	=	"gl_reload",
	gl_reloadempty	=	"gl_reloadempty",
	gl_sprint	=	"gl_sprint",
	gl_iron_down	=	"gl_iron_down",
	gl_iron_dryfire	=	"gl_iron_dryfire",
	gl_iron_fire	=	"gl_iron_fire",
	gl_iron_fireselect	=	"gl_iron_fireselect",
	
	glsetup_crawl	=	"glsetup_crawl",
	glsetup_down	=	"glsetup_down",
	glsetup_draw	=	"glsetup_draw",
	glsetup_dryfire	=	"glsetup_dryfire",
	glsetup_fire	=	"glsetup_fire",
	glsetup_holster	=	"glsetup_holster",
	glsetup_in	=	"glsetup_in",
	glsetup_out	=	"glsetup_out",
	glsetup_ready	=	"glsetup_ready",
	glsetup_reload	=	"glsetup_reload",
	glsetup_sprint	=	"glsetup_sprint",
	glsetup_iron_down	=	"glsetup_iron_down",
	glsetup_iron_dryfire	=	"glsetup_iron_dryfire",
	glsetup_iron_fire	=	"glsetup_iron_fire",
	
	iron_down	=	"iron_down",
	iron_dryfire	=	"iron_dryfire",
	iron_fire	=	"iron_fire",
	iron_fireselect	=	"iron_fireselect",
}
