SWEP.Sequences = {
	base_crawl	=	"base_crawl",
	base_down	=	"base_down",
	base_draw	=	"base_draw",
	base_dryfire	=	"base_dryfire",
	base_fire	=	"base_fire",
	base_fireselect	=	"base_fireselect",
	base_holster	=	"base_holster",
	base_idle	=	"base_idle",
	base_ready	=	"base_ready",
	base_reload	=	"base_reload",
	base_reload_extmag	=	"base_reload_ext",
	base_reloadempty	=	"base_reloadempty",
	base_reloadempty_extmag	=	"base_reloadempty_ext",
	base_sprint	=	"base_sprint",
	
	deployed_dryfire	=	"deployed_dryfire",
	deployed_fire	=	"deployed_fire",
	deployed_fireselect	=	"deployed_fireselect",
	deployed_idle	=	"deployed_idle",
	deployed_in	=	"deployed_in",
	deployed_out	=	"deployed_out",
	deployed_reload	=	"deployed_reload",
	deployed_reload_extmag	=	"deployed_reload_ext",
	deployed_reloadempty	=	"deployed_reloadempty",
	deployed_reloadempty_extmag	=	"deployed_reloadempty_ext",
	
	deployed_iron_dryfire	=	"deployed_iron_dryfire",
	deployed_iron_fire	=	"deployed_iron_fire",
	deployed_iron_fireselect	=	"deployed_iron_fireselect",
	
	foregrip_crawl	=	"foregrip_crawl",
	foregrip_down	=	"foregrip_down",
	foregrip_draw	=	"foregrip_draw",
	foregrip_dryfire	=	"foregrip_dryfire",
	foregrip_fire	=	"foregrip_fire",
	foregrip_fireselect	=	"foregrip_fireselect",
	foregrip_holster	=	"foregrip_holster",
	foregrip_ready	=	"foregrip_ready",
	foregrip_reload	=	"foregrip_reload",
	foregrip_reload_extmag	=	"foregrip_reload_ext",
	foregrip_reloadempty	=	"foregrip_reloadempty",
	foregrip_reloadempty_extmag	=	"foregrip_reloadempty_ext",
	foregrip_sprint	=	"foregrip_sprint",
	
	foregrip_iron_down	=	"foregrip_iron_down",
	foregrip_iron_dryfire	=	"foregrip_iron_dryfire_b",
	foregrip_iron_fire	=	"foregrip_iron_fire",
	foregrip_iron_fireselect	=	"foregrip_iron_fireselect_b",
	
	iron_down	=	"iron_down",
	iron_dryfire	=	"iron_dryfire",
	-- iron_fire	=	"iron_fire",
	iron_fire	=	{"iron_fire_a", "iron_fire_b", "iron_fire_c", "iron_fire_d", "iron_fire_e", "iron_fire_f"},
	iron_fire_a	=	"iron_fire_a",
	iron_fire_b	=	"iron_fire_b",
	iron_fire_c	=	"iron_fire_c",
	iron_fire_d	=	"iron_fire_d",
	iron_fire_e	=	"iron_fire_e",
	iron_fire_f	=	"iron_fire_f",
	iron_fireselect	=	"iron_fireselect",
}
