local particlefiles = {
    -- "ammo_cache_ins.pcf",
    -- "blood_fx.pcf",
    -- "blood_impact.pcf",
    -- "burning_fx.pcf",
    -- "environment_fx.pcf",
    -- "environmental_fx.pcf",
    -- "error.pcf",
    -- "explosion_fx_ins.pcf",
    -- "explosion_fx_ins_b.pcf",
    -- "fire_01.pcf",
    -- "fire_01_ins.pcf",
    -- "fire_01_unused.pcf",
    -- "fire_01l4d.pcf",
    -- "flashlight.pcf",
    -- "footstep_fx.pcf",
    -- "impact_fx_ins.pcf",
    -- "ins_burning_fx.pcf",
    -- "ins_light_fx.pcf",
    -- "ins_rockettrail.pcf",
    -- "ins_smokegrenade.pcf",
    -- "insect_fx.pcf",
    -- "jonny_light_rigs.pcf",
    -- "light_fx.pcf",
    -- "menu.pcf",
    -- "rain_fx.pcf",
    -- "rain_fx_unused.pcf",
    -- "rope_fx.pcf",
    -- "screen_fx.pcf",
    -- "snow_fx_unused.pcf",
    -- "spark_fx.pcf",
    -- "steamworks.pcf",
    -- "water_fx.pcf",
    -- "water_impact.pcf",
    -- "weapon_fx.pcf",
    "weapon_fx_ins.pcf",
    -- "weapon_fx_ins_b.pcf",
    -- "weapon_fx_tracers.pcf",
    -- "world_fx_ins.pcf",
}

for k, v in pairs(particlefiles) do
	game.AddParticles("particles/gmod4phun/ins2/"..v)
end

local particlenames = {
    // weapon_fx_ins
    "pb_ins2_ins_weapon_at4_frontblast",
    "pb_ins2_ins_weapon_rpg_backblast",
    "pb_ins2_ins_weapon_rpg_dust",
    "pb_ins2_ins_weapon_rpg_flame",
    "pb_ins2_ins_weapon_rpg_flash",
    "pb_ins2_ins_weapon_rpg_frontblast",
    "pb_ins2_ins_weapon_rpg_frontblast_smoke",
    "pb_ins2_ins_weapon_rpg_frontblast_trail",
    "pb_ins2_ins_weapon_rpg_mf_solid",
    "pb_ins2_ins_weapon_rpg_muzzleflash",
    "pb_ins2_ins_weapon_rpg_muzzleflash_b",
    "pb_ins2_ins_weapon_rpg_muzzleflash_frontcover",
    "pb_ins2_ins_weapon_rpg_muzzleflash_sparks",
    "pb_ins2_ins_weapon_rpg_smoke",
    "pb_ins2_ins_weapon_rpg_smoke_linger",
    "pb_ins2_ins_weapon_rpg_smoketrail",
    "pb_ins2_ins_weapon_rpg_spark",
    "pb_ins2_ins_weapon_screen_flash",
    "pb_ins2_molotov_drips",
    "pb_ins2_molotov_glow",
    "pb_ins2_molotov_lighter",
    "pb_ins2_molotov_lighter_b",
    "pb_ins2_molotov_lighter_c",
    "pb_ins2_molotov_lighter_d",
    "pb_ins2_molotov_lighter_e",
    "pb_ins2_molotov_lighter_sparks",
    "pb_ins2_molotov_rag",
    "pb_ins2_molotov_rag_b",
    "pb_ins2_molotov_rag_c",
    "pb_ins2_molotov_rag_d",
    "pb_ins2_molotov_rag_ribbon",
    "pb_ins2_molotov_rag_ribbon_b",
    "pb_ins2_molotov_rag_ribbon_c",
    "pb_ins2_molotov_trail",
    "pb_ins2_molotov_trail_b",
    "pb_ins2_molotov_trail_fire",
    "pb_ins2_molotov_trail_smoke",
    "pb_ins2_molotov_trail_test",
    "pb_ins2_muzzleflash_1p_glow",
    "pb_ins2_muzzleflash_akm_1p",
    "pb_ins2_muzzleflash_akm_1p_b",
    "pb_ins2_muzzleflash_akm_1p_core",
    "pb_ins2_muzzleflash_akm_1p_core_b",
    "pb_ins2_muzzleflash_akm_1p_flame",
    "pb_ins2_muzzleflash_akm_1p_flame_b",
    "pb_ins2_muzzleflash_akm_1p_glow",
    "pb_ins2_muzzleflash_akm_1p_linger",
    "pb_ins2_muzzleflash_akm_1p_sparks",
    "pb_ins2_muzzleflash_akm_3p_core",
    "pb_ins2_muzzleflash_akm_3p_flame",
    "pb_ins2_muzzleflash_akm_3p_glow",
    "pb_ins2_muzzleflash_akm_3p_sparks",
    "pb_ins2_muzzleflash_akm_3rd",
    "pb_ins2_muzzleflash_dust_kickup",
    "pb_ins2_muzzleflash_empty",
    "pb_ins2_muzzleflash_fal_1p",
    "pb_ins2_muzzleflash_fal_1p_b",
    "pb_ins2_muzzleflash_fal_1p_core",
    "pb_ins2_muzzleflash_fal_1p_splits",
    "pb_ins2_muzzleflash_fal_3p_sparks_a",
    "pb_ins2_muzzleflash_fal_3p_sparks_b",
    "pb_ins2_muzzleflash_fal_3p_sparks_c",
    "pb_ins2_muzzleflash_fal_3p_sparks_d",
    "pb_ins2_muzzleflash_fal_3p_splits_a",
    "pb_ins2_muzzleflash_fal_3p_splits_b",
    "pb_ins2_muzzleflash_fal_3p_splits_c",
    "pb_ins2_muzzleflash_fal_3p_splits_d",
    "pb_ins2_muzzleflash_fal_3rd",
    "pb_ins2_muzzleflash_m14_1p",
    "pb_ins2_muzzleflash_m14_1p_b",
    "pb_ins2_muzzleflash_m14_1p_core",
    "pb_ins2_muzzleflash_m14_1p_splits",
    "pb_ins2_muzzleflash_m14_3p_splits_a",
    "pb_ins2_muzzleflash_m14_3p_splits_b",
    "pb_ins2_muzzleflash_m14_3p_splits_c",
    "pb_ins2_muzzleflash_m14_3p_splits_d",
    "pb_ins2_muzzleflash_m14_3rd",
    "pb_ins2_muzzleflash_m16_1p",
    "pb_ins2_muzzleflash_m16_1p_b",
    "pb_ins2_muzzleflash_m16_1p_core",
    "pb_ins2_muzzleflash_m16_1p_core_b",
    "pb_ins2_muzzleflash_m16_1p_flame",
    "pb_ins2_muzzleflash_m16_1p_glow",
    "pb_ins2_muzzleflash_m16_1p_linger",
    "pb_ins2_muzzleflash_m16_1p_sparks",
    "pb_ins2_muzzleflash_m16_1p_splits",
    "pb_ins2_muzzleflash_m16_3p_core",
    "pb_ins2_muzzleflash_m16_3p_flame",
    "pb_ins2_muzzleflash_m16_3p_glow",
    "pb_ins2_muzzleflash_m16_3p_splits_a",
    "pb_ins2_muzzleflash_m16_3p_splits_b",
    "pb_ins2_muzzleflash_m16_3p_splits_c",
    "pb_ins2_muzzleflash_m16_3p_splits_d",
    "pb_ins2_muzzleflash_m16_3p_splits_e",
    "pb_ins2_muzzleflash_m16_3rd",
    "pb_ins2_muzzleflash_m249_1p",
    "pb_ins2_muzzleflash_m249_1p_b",
    "pb_ins2_muzzleflash_m249_1p_c",
    "pb_ins2_muzzleflash_m249_1p_core",
    "pb_ins2_muzzleflash_m249_1p_core_2",
    "pb_ins2_muzzleflash_m249_1p_core_b",
    "pb_ins2_muzzleflash_m249_1p_flame",
    "pb_ins2_muzzleflash_m249_1p_glow",
    "pb_ins2_muzzleflash_m249_1p_spark_trail",
    "pb_ins2_muzzleflash_m249_1p_sparks",
    "pb_ins2_muzzleflash_m249_1p_splits",
    "pb_ins2_muzzleflash_m249_1p_splits_b",
    "pb_ins2_muzzleflash_m249_1p_splits_c",
    "pb_ins2_muzzleflash_m249_3p_splits",
    "pb_ins2_muzzleflash_m249_3rd",
    "pb_ins2_muzzleflash_m590_1p",
    "pb_ins2_muzzleflash_m590_1p_core",
    "pb_ins2_muzzleflash_m590_1p_glow",
    "pb_ins2_muzzleflash_m590_1p_linger",
    "pb_ins2_muzzleflash_m590_1p_sparks",
    "pb_ins2_muzzleflash_m590_1p_sparks_b",
    "pb_ins2_muzzleflash_m590_3p_core",
    "pb_ins2_muzzleflash_m590_3p_sparks",
    "pb_ins2_muzzleflash_m590_3rd",
    "pb_ins2_muzzleflash_m9_1p",
    "pb_ins2_muzzleflash_m9_1p_b",
    "pb_ins2_muzzleflash_m9_1p_core",
    "pb_ins2_muzzleflash_m9_1p_flame",
    "pb_ins2_muzzleflash_m9_1p_glow",
    "pb_ins2_muzzleflash_m9_1p_linger",
    "pb_ins2_muzzleflash_m9_1p_sparks",
    "pb_ins2_muzzleflash_m9_3p_core",
    "pb_ins2_muzzleflash_m9_3p_glow",
    "pb_ins2_muzzleflash_m9_3rd",
    "pb_ins2_muzzleflash_makarov_1p",
    "pb_ins2_muzzleflash_makarov_1p_b",
    "pb_ins2_muzzleflash_makarov_1p_core",
    "pb_ins2_muzzleflash_makarov_1p_flame",
    "pb_ins2_muzzleflash_makarov_1p_glow",
    "pb_ins2_muzzleflash_makarov_1p_sparks",
    "pb_ins2_muzzleflash_makarov_3p_core",
    "pb_ins2_muzzleflash_makarov_3p_glow",
    "pb_ins2_muzzleflash_makarov_3rd",
    "pb_ins2_muzzleflash_mp40_1p",
    "pb_ins2_muzzleflash_mp40_1p_core",
    "pb_ins2_muzzleflash_mp40_1p_flame",
    "pb_ins2_muzzleflash_mp40_1p_glow",
    "pb_ins2_muzzleflash_mp40_1p_sparks",
    "pb_ins2_muzzleflash_mp40_3p_core",
    "pb_ins2_muzzleflash_mp40_3p_flame",
    "pb_ins2_muzzleflash_mp40_3rd",
    "pb_ins2_muzzleflash_mp5_1p",
    "pb_ins2_muzzleflash_mp5_1p_core",
    "pb_ins2_muzzleflash_mp5_1p_flame",
    "pb_ins2_muzzleflash_mp5_1p_glow",
    "pb_ins2_muzzleflash_mp5_1p_sparks",
    "pb_ins2_muzzleflash_mp5_3rd",
    "pb_ins2_muzzleflash_sks_1p",
    "pb_ins2_muzzleflash_sks_1p_core",
    "pb_ins2_muzzleflash_sks_1p_core_b",
    "pb_ins2_muzzleflash_sks_1p_flame",
    "pb_ins2_muzzleflash_sks_1p_glow",
    "pb_ins2_muzzleflash_sks_1p_sparks",
    "pb_ins2_muzzleflash_sks_3p_core",
    "pb_ins2_muzzleflash_sks_3rd",
    "pb_ins2_muzzleflash_smoke_large_linger",
    "pb_ins2_muzzleflash_smoke_medium_linger",
    "pb_ins2_muzzleflash_smoke_medium_variant_1",
    "pb_ins2_muzzleflash_smoke_small_variant_1",
    "pb_ins2_muzzleflash_smoke_small_variant_2",
    "pb_ins2_muzzleflash_smoke_small_variant_3",
    "pb_ins2_muzzleflash_smoke_small_variant_4",
    "pb_ins2_muzzleflash_smoke_small_variant_5",
    "pb_ins2_muzzleflash_smoke_tiny",
    "pb_ins2_muzzleflash_spark_trail",
    "pb_ins2_muzzleflash_spark_trail_3p",
    "pb_ins2_muzzleflash_spark_trail_b",
    "pb_ins2_muzzleflash_spark_trail_b_3p",
    "pb_ins2_muzzleflash_spark_trail_c",
    "pb_ins2_muzzleflash_sparks_variant_1",
    "pb_ins2_muzzleflash_sparks_variant_6",
    "pb_ins2_muzzleflash_suppressed_1p",
    "pb_ins2_muzzleflash_toz_1p",
    "pb_ins2_muzzleflash_toz_1p_core",
    "pb_ins2_muzzleflash_toz_1p_glow",
    "pb_ins2_muzzleflash_toz_1p_main",
    "pb_ins2_muzzleflash_toz_1p_sparks",
    "pb_ins2_muzzleflash_toz_1p_sparks_b",
    "pb_ins2_muzzleflash_toz_3p_core",
    "pb_ins2_muzzleflash_toz_3rd",
    "pb_ins2_muzzleflash_tracer",
    "pb_ins2_muzzleflash_tracer_3p",
    "pb_ins2_muzzleflash_ump_1p",
    "pb_ins2_muzzleflash_ump_1p_core",
    "pb_ins2_muzzleflash_ump_1p_flame",
    "pb_ins2_muzzleflash_ump_1p_sparks",
    "pb_ins2_muzzleflash_ump_3rd",
    "pb_ins2_shell_eject",
    "pb_ins2_shell_eject_b",
    "pb_ins2_shell_eject_c",
    "pb_ins2_weapon_muzzle_smoke",
    "pb_ins2_weapon_muzzle_smoke_b",
    "pb_ins2_weapon_muzzle_smoke_c",
}

for k, v in pairs(particlenames) do
	PrecacheParticleSystem(v)
end
