SWEP.Sequences = {
	base_idle = "base_idle",
	base_ready = "base_ready",
	base_draw = "base_draw",
	base_holster = "base_holster",
	base_down = "base_down",
	base_crawl = "base_crawl",
	base_fire = {"base_fire_1", "base_fire_2"},
	base_fire_cock = {"base_fire_cock_1", "base_fire_cock_2"},
	base_firelast = "base_firelast",
	base_dryfire = "base_dryfire",
	base_reload_start = "base_reload_start",
	base_reload_start_empty = "base_reload_start_empty",
	base_reload_insert = "base_reload_insert",
	base_reload_end = "base_reload_end",
	base_reload_end_empty = "base_reload_end_empty",
	base_sprint = "base_sprint",
	
	empty_idle = "base_idle",
	empty_draw = "base_draw",
	empty_holster = "base_holster",
	empty_down = "base_down",
	empty_crawl = "base_crawl",
	empty_sprint = "base_sprint",
	
	iron_down = "iron_down",
	empty_iron_down = "empty_iron_down",
	
	iron_fire = {"iron_fire_1", "iron_fire_2"},
	iron_fire_cock = {"iron_fire_cock_1", "iron_fire_cock_2"},
	iron_firelast = "iron_fire_last",
	iron_dryfire = "iron_dryfire",
	
	foregrip_draw = "foregrip_draw",
	foregrip_holster = "foregrip_holster",
	foregrip_down = "foregrip_down",
	foregrip_ready = "foregrip_ready",
	foregrip_crawl = "foregrip_crawl",
	
	foregrip_fire = {"foregrip_fire_1", "foregrip_fire_2"},
	foregrip_fire_cock = {"foregrip_fire_cock_1", "foregrip_fire_cock_2"},
	foregrip_firelast = "foregrip_firelast",
	foregrip_dryfire = "foregrip_dryfire",
	
	foregrip_reload_start = "foregrip_reload_start",
	foregrip_reload_start_empty = "foregrip_reload_start_empty",
	foregrip_reload_insert = "foregrip_reload_insert",
	foregrip_reload_end = "foregrip_reload_end",
	foregrip_reload_end_empty = "foregrip_reload_end_empty",
	foregrip_sprint = "foregrip_sprint",
	
	foregrip_iron_down = "foregrip_iron_down",
	foregrip_iron_down_empty = "foregrip_iron_down",
	
	foregrip_iron_fire = {"foregrip_iron_fire_1", "foregrip_iron_fire_2"},
	foregrip_iron_fire_cock = {"foregrip_iron_fire_cock_1", "foregrip_iron_fire_cock_2"},
	foregrip_iron_firelast = "foregrip_iron_firelast",
	foregrip_iron_dryfire = "foregrip_iron_dryfire",
}
