SWEP.Sequences = {
    base_crawl	=	"base_crawl",
    base_down	=	"base_down",
    base_draw	=	"base_draw",
    base_dryfire	=	"base_dryfire",
    base_fire   =   {"base_fire_1", "base_fire_2", "base_fire_3"},
    base_fire_1	=	"base_fire_1",
    base_fire_2	=	"base_fire_2",
    base_fire_3	=	"base_fire_3",
    base_holster	=	"base_holster",
    base_idle	=	"base_idle",
    base_ready	=	"base_ready",
    base_reload	=	"base_reload",
    base_reloadempty	=	"base_reload_empty",
    base_reload_half	=	"base_reload_half",
    base_sprint	=	"base_sprint",

    deployed_dryfire	=	"deployed_dryfire",
    deployed_fire_1	=	"deployed_fire_1",
    deployed_fire_2	=	"deployed_fire_2",
    deployed_idle	=	"deployed_idle",
    deployed_in	=	"deployed_in",
    deployed_iron_dryfire	=	"deployed_iron_dryfire",
    deployed_iron_fire_1	=	"deployed_iron_fire_1",
    deployed_iron_fire_2	=	"deployed_iron_fire_2",
    deployed_iron_idle	=	"deployed_iron_idle",
    deployed_out	=	"deployed_out",
    deployed_reload	=	"deployed_reload",
    deployed_reload_empty	=	"deployed_reload_empty",
    deployed_reload_half	=	"deployed_reload_half",
    
    idle	=	"idle",
    idle_deployed	=	"idle_deployed",
    iron	=	"iron",
    iron_deployed	=	"iron_deployed",
    iron_down	=	"iron_down",
    iron_dryfire	=	"iron_dryfire",
    
    iron_fire   =   {"iron_fire_1", "iron_fire_2", "iron_fire_3", "iron_fire_4"},
    iron_fire_1	=	"iron_fire_1",
    iron_fire_2	=	"iron_fire_2",
    iron_fire_3	=	"iron_fire_3",
    iron_fire_4	=	"iron_fire_4",
}
