SWEP.Sequences = {
	base_crawl	=	"base_crawl",
	base_down	=	"base_down",
	base_draw	=	"base_draw",
	base_dryfire	=	"base_dryfire",
	base_fire	=	"base_fire",
	base_holster	=	"base_holster",
	base_idle	=	"base_idle",
	base_ready	=	"base_ready",
	base_reload	=	"base_reload",
	base_reload_extmag	=	"base_reload_ext",
	base_reloadempty	=	"base_reloadempty",
	base_reloadempty_extmag	=	"base_reloadempty_ext",
	base_sprint	=	"base_sprint",
	
	foregrip_crawl	=	"foregrip_crawl",
	foregrip_down	=	"foregrip_down",
	foregrip_draw	=	"foregrip_draw",
	foregrip_dryfire	=	"foregrip_dryfire",
	foregrip_fire	=	"foregrip_fire",
	foregrip_holster	=	"foregrip_holster",
	foregrip_ready	=	"foregrip_ready",
	foregrip_reload	=	"foregrip_reload",
	foregrip_reload_extmag	=	"foregrip_reload_ext",
	foregrip_reloadempty	=	"foregrip_reloadempty",
	foregrip_reloadempty_extmag	=	"foregrip_reloadempty_ext",
	foregrip_sprint	=	"foregrip_sprint",
	
	foregrip_iron_down	=	"foregrip_iron_down",
	foregrip_iron_dryfire	=	"foregrip_iron_dryfire",
	foregrip_iron_fire	=	"foregrip_iron_fire",
	
	iron_down	=	"iron_down",
	iron_dryfire	=	"iron_dryfire",
	iron_fire	=	"iron_fire",
}
