SWEP.Sequences = {
	base_crawl	=	"base_crawl",
	base_down	=	"base_down",
	base_draw	=	"base_draw",
	base_dryfire	=	"base_dryfire",
	base_fire	=	"base_fire",
	base_fireselect	=	"base_fireselect",
	base_holster	=	"base_holster",
	base_idle	=	"base_idle",
	base_ready	=	"base_ready",
	base_reload	=	"base_reload",
	base_reload_drum	=	"base_reload_drum",
	base_reloadempty	=	"base_reloadempty",
	base_reloadempty_drum	=	"base_reloadempty_drum",
	base_sprint	=	"base_sprint",

	deployed_dryfire	=	"deployed_dryfire",
	deployed_fire	=	"deployed_fire",
	deployed_fireselect	=	"deployed_fireselect",
	deployed_idle	=	"deployed_idle",
	deployed_in	=	"deployed_in",
	deployed_out	=	"deployed_out",
	
	deployed_iron	=	"deployed_iron",
	deployed_iron_dryfire	=	"deployed_iron_dryfire",
	deployed_iron_fire	=	{"deployed_iron_fire_a", "deployed_iron_fire_b", "deployed_iron_fire_c"},
	deployed_iron_fire_a	=	"deployed_iron_fire_a",
	deployed_iron_fire_b	=	"deployed_iron_fire_b",
	deployed_iron_fire_c	=	"deployed_iron_fire_c",
	deployed_iron_fireselect	=	"deployed_iron_fireselect",
	
	deployed_reload	=	"deployed_reload",
	deployed_reload_drum	=	"deployed_reload_drum",
	deployed_reloadempty	=	"deployed_reload_empty",
	deployed_reloadempty_drum	=	"deployed_reload_empty_drum",
	
	foregrip_crawl	=	"foregrip_crawl",
	foregrip_down	=	"foregrip_down",
	foregrip_draw	=	"foregrip_draw",
	foregrip_dryfire	=	"foregrip_dryfire",
	foregrip_fire	=	"foregrip_fire",
	foregrip_fireselect	=	"foregrip_fireselect",
	foregrip_holster	=	"foregrip_holster",
	
	foregrip_iron_down	=	"foregrip_iron_down",
	foregrip_iron_dryfire	=	"foregrip_iron_dryfire",
	
	foregrip_iron_fire	=	{"foregrip_iron_fire_a", "foregrip_iron_fire_b", "foregrip_iron_fire_c"},
	foregrip_iron_fire_a	=	"foregrip_iron_fire_a",
	foregrip_iron_fire_b	=	"foregrip_iron_fire_b",
	foregrip_iron_fire_c	=	"foregrip_iron_fire_c",
	foregrip_iron_fireselect	=	"foregrip_iron_fireselect",
	
	foregrip_ready	=	"foregrip_ready",
	foregrip_reload	=	"foregrip_reload",
	foregrip_reload_drum	=	"foregrip_reload_drum",
	foregrip_reloadempty	=	"foregrip_reloadempty",
	foregrip_reloadempty_drum	=	"foregrip_reloadempty_drum",
	foregrip_sprint	=	"foregrip_sprint",
	
	iron_down	=	"iron_down",
	iron_dryfire	=	"iron_dryfire",
	iron_fire	=	{"iron_fire_a", "iron_fire_b", "iron_fire_c"},
	iron_fire_a	=	"iron_fire_a",
	iron_fire_b	=	"iron_fire_b",
	iron_fire_c	=	"iron_fire_c",
	iron_fireselect	=	"iron_fireselect",
}
