SWEP.UsesEmptyAnims = true

SWEP.Sequences = {
	base_crawl	=	"base_crawl",
	base_down	=	"base_down",
	base_draw	=	"base_draw",
	base_dryfire	=	"base_dryfire",
	base_fire	=	"base_fire",
	base_firelast	=	"base_firelast",
	base_holster	=	"base_holster",
	base_idle	=	"base_idle",
	base_ready	=	"base_ready",
	base_reload	=	"base_reload",
	base_reloadempty	=	"base_reloadempty",
	base_sprint	=	"base_sprint",
	
	empty_crawl	=	"empty_crawl",
	empty_down	=	"empty_down",
	empty_draw	=	"empty_draw",
	empty_holster	=	"empty_holster",
	empty_idle	=	"empty_idle",
	empty_layer	=	"empty_layer",
	empty_sprint	=	"empty_sprint",
	empty_iron_down	=	"iron_empty_down",
	empty_iron_idle	=	"iron_empty_idle",
	
	iron_down	=	"iron_down",
	iron_dryfire	=	"iron_dryfire",
	iron_fire	=	"iron_fire",
	iron_fire_a	=	"iron_fire_a",
	iron_fire_b	=	"iron_fire_b",
	iron_fire_c	=	"iron_fire_c",
	iron_fire_d	=	"iron_fire_d",
	iron_fire_e	=	"iron_fire_e",
	iron_fire_f	=	"iron_fire_f",
	iron_firelast	=	"iron_firelast",
}
