SWEP.Sequences = {
	base_crawl	=	"base_crawl",
	base_down	=	"base_down",
	base_draw	=	"base_draw",
	base_dryfire	=	"base_dryfire",
	base_fire	=	"base_fire",
	base_fireselect	=	"base_fireselect",
	base_holster	=	"base_holster",
	base_idle	=	"base_idle",
	base_ready	=	"base_ready",
	base_reload	=	"base_reload",
	base_reloadempty	=	"base_reloadempty",
	base_sprint	=	"base_sprint",
	
	deployed_dryfire	=	"deployed_dryfire",
	deployed_fire	=	"deployed_fire",
	deployed_fireselect	=	"deployed_fireselect",
	deployed_idle	=	"deployed_idle",
	deployed_in	=	"deployed_in",
	deployed_out	=	"deployed_out",
	deployed_reload	=	"deployed_reload",
	deployed_reloadempty	=	"deployed_reloadempty",
	
	deployed_iron_dryfire	=	"deployed_iron_dryfire",
	deployed_iron_fire	=	{"deployed_iron_fire_1", "deployed_iron_fire_2"},
	deployed_iron_fire_1	=	"deployed_iron_fire_1",
	deployed_iron_fire_2	=	"deployed_iron_fire_2",
	deployed_iron_fireselect	=	"deployed_iron_fireselect",
	deployed_iron_idle	=	"deployed_iron_idle",
	
	iron_down	=	"iron_down",
	iron_dryfire	=	"iron_dryfire",
	iron_fire	=	{"iron_fire_1", "iron_fire_2", "iron_fire_3", "iron_fire_4"},
	iron_fire_1	=	"iron_fire_1",
	iron_fire_2	=	"iron_fire_2",
	iron_fire_3	=	"iron_fire_3",
	iron_fire_4	=	"iron_fire_4",
	iron_fireselect	=	"iron_fireselect",
}
